// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk4eD5FNOt5fCHChizGsGGsK0ZYz9p7mE',
    appId: '1:943799206739:web:12cc67c9bbc7d0d72dd7a6',
    messagingSenderId: '943799206739',
    projectId: 'notes-assignment-app',
    authDomain: 'notes-assignment-app.firebaseapp.com',
    storageBucket: 'notes-assignment-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy6QA806w44-fXfsm_xGXvNn3Vw1mlIkQ',
    appId: '1:943799206739:android:2820028b8b0de7b52dd7a6',
    messagingSenderId: '943799206739',
    projectId: 'notes-assignment-app',
    storageBucket: 'notes-assignment-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZYX8hyZImx3NHteWbyclWBvP96x6LI1k',
    appId: '1:943799206739:ios:3b3a7f7b45275b372dd7a6',
    messagingSenderId: '943799206739',
    projectId: 'notes-assignment-app',
    storageBucket: 'notes-assignment-app.firebasestorage.app',
    iosBundleId: 'com.example.personalassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZYX8hyZImx3NHteWbyclWBvP96x6LI1k',
    appId: '1:943799206739:ios:3b3a7f7b45275b372dd7a6',
    messagingSenderId: '943799206739',
    projectId: 'notes-assignment-app',
    storageBucket: 'notes-assignment-app.firebasestorage.app',
    iosBundleId: 'com.example.personalassignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk4eD5FNOt5fCHChizGsGGsK0ZYz9p7mE',
    appId: '1:943799206739:web:4057bcb3d4c54df52dd7a6',
    messagingSenderId: '943799206739',
    projectId: 'notes-assignment-app',
    authDomain: 'notes-assignment-app.firebaseapp.com',
    storageBucket: 'notes-assignment-app.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAk4eD5FNOt5fCHChizGsGGsK0ZYz9p7mE',
    appId: '1:943799206739:linux:4057bcb3d4c54df52dd7a6',
    messagingSenderId: '943799206739',
    projectId: 'notes-assignment-app',
    authDomain: 'notes-assignment-app.firebaseapp.com',
    storageBucket: 'notes-assignment-app.firebasestorage.app',
  );
}